# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Page1.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setFamily(u"Tw Cen MT")
        font.setPointSize(9)
        font.setItalic(False)
        font.setKerning(False)
        MainWindow.setFont(font)
        MainWindow.setTabletTracking(False)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setStyleSheet(u"background-color: rgb(170, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 5;\n"
"border-style: solid;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 20, 291, 51))
        font1 = QFont()
        font1.setFamily(u"Tw Cen MT Condensed")
        font1.setPointSize(26)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:1 rgba(108, 108, 108, 0));")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(260, 80, 281, 31))
        font2 = QFont()
        font2.setFamily(u"Tw Cen MT Condensed")
        font2.setPointSize(12)
        self.label_2.setFont(font2)
        self.label_2.setMouseTracking(True)
        self.label_2.setTabletTracking(False)
        self.label_2.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:1 rgba(108, 108, 108, 0));")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(170, 110, 511, 21))
        self.label_3.setFont(font2)
        self.label_3.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:1 rgba(108, 108, 108, 0));")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(True)
        self.frame.setGeometry(QRect(140, 190, 220, 251))
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setSizeIncrement(QSize(0, 0))
        self.frame.setBaseSize(QSize(0, 0))
        self.frame.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(u"background-color: rgb(175, 210, 255);\n"
"QFrame.Panel | QFrame.Raised")
        self.frame.setInputMethodHints(Qt.ImhNone)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(80, 20, 81, 16))
        font3 = QFont()
        font3.setFamily(u"Tw Cen MT")
        font3.setPointSize(11)
        self.label_5.setFont(font3)
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(60, 200, 93, 28))
        self.pushButton.setFont(font3)
        self.pushButton.setStyleSheet(u"background-color: rgb(152, 183, 221);")
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 60, 151, 22))
        font4 = QFont()
        font4.setFamily(u"Tw Cen MT")
        font4.setPointSize(9)
        self.lineEdit.setFont(font4)
        self.lineEdit.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.lineEdit_2 = QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(40, 110, 151, 22))
        self.lineEdit_2.setFont(font4)
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.lineEdit_3 = QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(40, 160, 151, 22))
        self.lineEdit_3.setFont(font4)
        self.lineEdit_3.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QRect(470, 190, 220, 201))
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setSizeIncrement(QSize(0, 0))
        self.frame_2.setBaseSize(QSize(0, 0))
        self.frame_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet(u"background-color: rgb(175, 210, 255);\n"
"")
        self.frame_2.setInputMethodHints(Qt.ImhNone)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(90, 10, 55, 31))
        self.label_4.setFont(font3)
        self.pushButton_2 = QPushButton(self.frame_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(60, 150, 93, 28))
        self.pushButton_2.setFont(font3)
        self.pushButton_2.setStyleSheet(u"background-color: rgb(152, 183, 221);")
        self.lineEdit_4 = QLineEdit(self.frame_2)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(40, 60, 131, 22))
        self.lineEdit_4.setFont(font4)
        self.lineEdit_4.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.lineEdit_5 = QLineEdit(self.frame_2)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(40, 110, 131, 22))
        self.lineEdit_5.setFont(font4)
        self.lineEdit_5.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(370, 490, 93, 28))
        font5 = QFont()
        font5.setFamily(u"Tw Cen MT")
        font5.setPointSize(12)
        self.pushButton_3.setFont(font5)
        self.pushButton_3.setStyleSheet(u"background-color: rgb(69, 137, 206);")
        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, -30, 801, 181))
        self.frame_5.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:1 rgba(108, 108, 108, 99));\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.499636, stop:1 rgba(247, 247, 246, 0));\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.499636, stop:1 rgba(246, 246, 247, 159));")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        MainWindow.setCentralWidget(self.centralwidget)
        self.frame_5.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.pushButton_3.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Agendamento virtual", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Seja bem vindo ao nosso agendamento virtual!", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Porfavor, insira as informa\u00e7\u00f5es necess\u00e1rias para dar prosseguimento ao agendamento: ", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Cadastro", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Cadastrar", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"Nome:", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.lineEdit_3.setText(QCoreApplication.translate("MainWindow", u"Senha:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Entrar", None))
        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u"Email:", None))
        self.lineEdit_5.setText(QCoreApplication.translate("MainWindow", u"Senha:", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Sair", None))
    # retranslateUi

